import torch
import torchvision.ops as ops

class OWOD_Labeler:
    def __init__(self, iou_known_thresh=0.5, iou_unknown_thresh=0.1, objectness_thresh=0.7):
        self.iou_known_thresh = iou_known_thresh
        self.iou_unknown_thresh = iou_unknown_thresh
        self.objectness_thresh = objectness_thresh

    def assign_labels_known_unknown_background(self, proposals, objectness_scores, gt_boxes, gt_labels):
          '''
          Categorizes RPN proposals into Known, Unknown, and Background classes.
          
          Args:
              proposals (Tensor[N, 4]): Bounding boxes generated by the Region Proposal Network (RPN).
              objectness_scores (Tensor[N]): Objectness scores corresponding to the proposals.
              gt_boxes (Tensor[M, 4]): Ground truth bounding boxes for the known classes in the image.
              gt_labels (Tensor[M]): Ground truth class labels corresponding to the gt_boxes.

          Returns:
              dict[str, Tensor]: A dictionary containing the categorized bounding boxes and labels
              with keys: 'known_boxes', 'known_labels', 'unknown_boxes', 'background_boxes'.
          '''

          # Edge case: no ground truth boxes present in the image.
          # Proposals are categorized as Unknown or Background strictly based on their objectness score.
          if len(gt_boxes) == 0:
              is_obj = objectness_scores >= self.objectness_thresh
              return {
                  "known_boxes": torch.empty((0, 4), device=proposals.device),
                  "known_labels": torch.empty((0,), dtype=torch.int64, device=proposals.device),
                  "unknown_boxes": proposals[is_obj],
                  "background_boxes": proposals[~is_obj]
              }

          # Compute the IoU matrix between all proposals and ground truth boxes [N_proposals, M_gts]
          iou_matrix = ops.box_iou(proposals, gt_boxes)
          
          # ====================================================================
          # 1. PROSPETTIVA PROPOSALS (Per trovare Unknown e Background)
          # Per ogni proposal, troviamo la sua IoU massima con qualsiasi GT
          # ====================================================================
          max_iou_per_prop, _ = iou_matrix.max(dim=1)

          # Unknown Mask: IoU trascurabile col GT (< iou_unknown_thresh) MA objectness ALTO (sicuramente un oggetto)
          unknown_mask = (max_iou_per_prop < self.iou_unknown_thresh) & (objectness_scores >= self.objectness_thresh)

          # Background Mask: IoU trascurabile col GT MA objectness BASSO (sicuramente sfondo/muro/cielo)
          background_mask = (max_iou_per_prop < self.iou_unknown_thresh) & (objectness_scores < self.objectness_thresh)

          # Nota: le proposal con (iou_unknown_thresh <= max_iou < iou_known_thresh) 
          # vengono silenziosamente scartate. Sono "ambigue" e non ci servono per il Representation Learning.

          # ====================================================================
          # 2. PROSPETTIVA GROUND TRUTH (Per trovare i Known 1-a-1 / "Hungarian")
          # Per ogni Ground Truth, troviamo l'indice della MIGLIOR proposal assoluta
          # ====================================================================
          best_iou_per_gt, best_prop_idx_per_gt = iou_matrix.max(dim=0)

          # Ci assicuriamo che questa miglior proposal abbia comunque una sovrapposizione decente (> iou_known_thresh)
          valid_gt_mask = best_iou_per_gt >= self.iou_known_thresh

          # Estraiamo gli indici delle proposal vincitrici
          best_known_indices = best_prop_idx_per_gt[valid_gt_mask]

          # Restituiamo il dizionario con tutto ciò che serve allo script principale
          return {
              "known_boxes": proposals[best_known_indices],
              "known_labels": gt_labels[valid_gt_mask], # Prendiamo i label solo dei GT che hanno trovato un match
              
              "unknown_boxes": proposals[unknown_mask],
              "unknown_scores": objectness_scores[unknown_mask], # AGGIUNTA FONDAMENTALE! Ci servirà per fare la NMS nello script principale
              
              "background_boxes": proposals[background_mask]
          }
