import torch
import torchvision.ops as ops

class OWOD_Labeler:
    def __init__(self, iou_known_thresh=0.5, iou_unknown_thresh=0.1, objectness_thresh=0.7):
        self.iou_known_thresh = iou_known_thresh
        self.iou_unknown_thresh = iou_unknown_thresh
        self.objectness_thresh = objectness_thresh

    def assign_labels_known_unknown_background(self, proposals, objectness_scores, gt_boxes, gt_labels):
          '''
          Categorizes RPN proposals into Known, Unknown, and Background classes.
          
          Args:
              proposals (Tensor[N, 4]): Bounding boxes generated by the Region Proposal Network (RPN).
              objectness_scores (Tensor[N]): Objectness scores corresponding to the proposals.
              gt_boxes (Tensor[M, 4]): Ground truth bounding boxes for the known classes in the image.
              gt_labels (Tensor[M]): Ground truth class labels corresponding to the gt_boxes.

          Returns:
              dict[str, Tensor]: A dictionary containing the categorized bounding boxes and labels
              with keys: 'known_boxes', 'known_labels', 'unknown_boxes', 'background_boxes'.
          '''

          # Edge case: no ground truth boxes present in the image.
          # Proposals are categorized as Unknown or Background strictly based on their objectness score.
          if len(gt_boxes) == 0:
              is_obj = objectness_scores >= self.objectness_thresh
              return {
                  "known_boxes": torch.empty((0, 4), device=proposals.device),
                  "known_labels": torch.empty((0,), dtype=torch.int64, device=proposals.device),
                  "unknown_boxes": proposals[is_obj],
                  "background_boxes": proposals[~is_obj]
              }

          # Compute the IoU matrix between all proposals and ground truth boxes [N_proposals, M_gts]
          iou_matrix = ops.box_iou(proposals, gt_boxes)
          
          # ====================================================================
          # 1. PROPOSALS PERSPECTIVE (To find Unknown and Background)
          # For each proposal, find its maximum IoU with any GT
          # ====================================================================
          max_iou_per_prop, _ = iou_matrix.max(dim=1)

          # Unknown Mask: Negligible IoU with GT (< iou_unknown_thresh) BUT HIGH objectness (definitely an object)
          unknown_mask = (max_iou_per_prop < self.iou_unknown_thresh) & (objectness_scores >= self.objectness_thresh)

          # Background Mask: Negligible IoU with GT AND LOW objectness (likely background/sky/wall)
          background_mask = (max_iou_per_prop < self.iou_unknown_thresh) & (objectness_scores < self.objectness_thresh)

          # Note: proposals with (iou_unknown_thresh <= max_iou < iou_known_thresh) 
          # are silently discarded. They are "ambiguous" and not useful for Representation Learning.

          # ====================================================================
          # 2. GROUND TRUTH PERSPECTIVE (To find 1-to-1 Known matches / "Hungarian")
          # For each Ground Truth, find the index of the absolute BEST proposal
          # ====================================================================
          best_iou_per_gt, best_prop_idx_per_gt = iou_matrix.max(dim=0)

          # Ensure that this best proposal has a decent overlap anyway (> iou_known_thresh)
          valid_gt_mask = best_iou_per_gt >= self.iou_known_thresh

          # Extract the indices of the winning proposals
          best_known_indices = best_prop_idx_per_gt[valid_gt_mask]

          # Return the dictionary with everything needed by the main script
          return {
              "known_boxes": proposals[best_known_indices],
              "known_labels": gt_labels[valid_gt_mask], # Take labels only from GTs that found a match
              
              "unknown_boxes": proposals[unknown_mask],
              "unknown_scores": objectness_scores[unknown_mask], # CRUCIAL ADDITION! Needed for NMS in main script
              
              "background_boxes": proposals[background_mask]
          }
